blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/arena-returns-934862812075917353
    about: Vous pouvez également nous faire parvenir vos bugs et suggestions sur notre Discord.
