# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/typechecking.yml'
      - '!.github/workflows/release.yml'
      - '**.md'
      - .editorconfig
      - .gitignore
      - '.idea/**'
      - '.vscode/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  draft_release:
    permissions:
      contents: write # Allows this job to create releases
    needs: [ lint ]  # Ensure draft_release only runs if lint succeeds
    uses: ./.github/workflows/release.yml
    with:
      dry-run: ${{ github.event_name != 'push' || github.ref_name != 'master' }}