# This workflow runs on every commit to master and every PR to master.
# It only compiles and tests - no deployment or artifacts.
name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  compile:
    uses: ./.github/workflows/compile.yml
    with:
      app-version: "dev-build"
      distribution-channel: "ci"
      upload-artifacts: false
