# Release workflow - creates GitHub releases
name: Release

on:
  workflow_call:
    inputs:
      app-version:
        required: true
        type: string
      distribution-channel:
        required: true
        type: string

permissions:
  contents: write

defaults:
  run:
    shell: "bash"

env:
  NODE_NO_WARNINGS: 1
  npm_config_audit: false
  npm_config_fund: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.distribution-channel}}
      url: https://github.com/${{github.repository}}/releases/tag/v${{inputs.app-version}}
    steps:
      - name: Download compiled app
        uses: actions/download-artifact@v5
        with:
          pattern: "*-${{inputs.distribution-channel}}"
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        run: |
          # Find all release files from Linux, MacOS and Windows builds
          FILES=$(find dist/ -name "ArenaReturnsLauncher*" -o -name "latest*.yml" -o -name "arena-returns-launcher*" | tr '\n' ' ')
          echo "Found release files: $FILES"
          gh release create v${{inputs.app-version}} $FILES --repo ${{github.repository}}
        env:
          GH_TOKEN: ${{ github.token }}
